### ISSUE TITLE
Unnable to make thriumph

### ISSUE THREAD

**Issue by pokoli** [pokoli/ButiJS#12]
The make thiumph event is not recived by the server, so we can not make any thriumph.

**Comment by pokoli** [comment]
On the lastest trunk the server gots the following error: 

/home/pokoli/udl/mepl/tfm/ButiJS/src/butifarraGame.js:102
        var roundScores=roundData.getScores();
                                  ^
TypeError: Object #<Object> has no method 'getScores'
    at [object Object].roundEnded (/home/pokoli/udl/mepl/tfm/ButiJS/src/butifarraGame.js:102:35)
    at [object Object].<anonymous> (/home/pokoli/udl/mepl/tfm/ButiJS/src/butifarraGame.js:152:18)
    at [object Object].<anonymous> (/home/pokoli/udl/mepl/tfm/ButiJS/src/butifarraGame.js:162:45)
    at [object Object].emit (events.js:70:17)
    at processGameEvent (/home/pokoli/udl/mepl/tfm/ButiJS/src/server.js:102:30)
    at Socket.<anonymous> (/home/pokoli/udl/mepl/tfm/ButiJS/src/server.js:231:55)
    at Socket.$emit (events.js:88:20)
    at SocketNamespace.handlePacket (/home/pokoli/udl/mepl/tfm/ButiJS/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/home/pokoli/udl/mepl/tfm/ButiJS/node_modules/socket.io/lib/manager.js:459:38)
    at WebSocket.onMessage (/home/pokoli/udl/mepl/tfm/ButiJS/node_modules/socket.io/lib/transport.js:387:20)

From the traceback it is executing the round-ended event.
