### ISSUE TITLE
Possible memory leak after playing 10 round

### ISSUE THREAD

**Issue by pokoli** [pokoli/ButiJS#40]
After playing 4 rounds we've got the following warning on the node console: 

(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
    at Socket.<anonymous> (events.js:133:17)
    at [object Object].<anonymous> (/home/pokoli/udl/mepl/tfm/ButiJS/src/server.js:165:20)
    at [object Object].emit (events.js:70:17)
    at [object Object].<anonymous> (events.js:108:8)
    at [object Object].startNewRound (/home/pokoli/udl/mepl/tfm/ButiJS/src/butifarraGame.js:238:18)
    at [object Object].emit (events.js:64:17)
    at [object Object].roundEnded (/home/pokoli/udl/mepl/tfm/ButiJS/src/butifarraGame.js:187:18)
    at [object Object].<anonymous> (/home/pokoli/udl/mepl/tfm/ButiJS/src/butifarraGame.js:211:18)
    at [object Object].emit (events.js:67:17)
    at [object Object].moveEnded (/home/pokoli/udl/mepl/tfm/ButiJS/src/butifarraRound.js:129:18)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

It means that there are listeners for the previous rouns that could be removed.

**Comment by pokoli** [comment]
On server.js we add a listener to the socket for every game event, but we never remove it.

```
    game.on('newListener',function(event,listener){
        socket.on(event,listener);
    });
```
